#!/bin/bash

# Credit: https://stackoverflow.com/a/246128
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# ensure:
# 1) has a value
# 2) ends with slash (/)
if [[ "$1" == "" || "$1" != */ ]];
then
	echo "usage: add-subversion-archive /path/to/svn-repo/ <option>"
	echo "usage: add-subversion-archive /path/to/svn-repo/ help"
	exit 1
fi

# Credit: https://stackoverflow.com/a/8063398/7163041
#contains() {
#    [[ $1 =~ (^|[[:space:]])$2($|[[:space:]]) ]] && exit(0) || exit(1)
#}

options=$(ls /usr/src/subversion-archive/)
#if [ $(contains $options "$2") ];
# Credit: https://stackoverflow.com/a/8063284/7163041
if [ $(echo $options | grep -w -q "$2"; echo $?) == 0 ];
then
    ARCHIVER="$2"
else #[[ "$2" == "help" || "$2" == "" ]];
	echo "usage: add-subversion-archive /path/to/svn-repo/ limit-history"
	echo "usage: add-subversion-archive /path/to/svn-repo/ limit-history <N>"
	echo "usage: add-subversion-archive /path/to/svn-repo/ limit-history 1"
	exit 1
fi

function install-post-commit {
    cd hooks/
    echo installing post-commit in $PWD
    if [ -f ./post-commit ]; then
       if [ -d ./post-commit.d/ ]; then
           ln -s /usr/src/subversion-archive/$ARCHIVER ./post-commit.d/subversion-archive_$ARCHIVER
        else
           echo "conflict!"
           exit 2
        fi
    else
       ln -s /usr/src/subversion-archive/$ARCHIVER post-commit
    fi
}

if [[ $ARCHIVER == 'limit-history' ]];
then
    # ensure:
    # 1) is a number (integer)
    # 2) is greater or equal to 1
    re='^\d+$'
    if [ "$3" == "" ];
    then
        ARCHIVE_RETAIN=1
    elif [[ "$3" =~ $re && "$3" != "0" ]];
    then
        ARCHIVE_RETAIN="$3"
    else
	    echo "usage: add-subversion-archive /path/to/svn-repo/ limit-history 1"
	    exit 1
    fi

    pushd "$1" > /dev/null
    install-post-commit

    cd ../conf/
    echo installing post-commit environment variables in $PWD
    echo "" >> $PWD/hooks-env
    echo "[post-commit]" >> $PWD/hooks-env
    echo "ArchiveRetain = $ARCHIVE_RETAIN" >> $PWD/hooks-env
    if [ ! -f $PWD/hooks-env ];
    then
        echo "Please manually create hooks-env"
        echo "echo '' >> $PWD/hooks-env"
        echo "echo '[post-commit]' >> $PWD/hooks-env"
        echo "echo 'ArchiveRetain = $ARCHIVE_RETAIN' >> $PWD/hooks-env"
    fi
    popd > /dev/null
fi

