#!/bin/bash
# see https://svnbook.red-bean.com/en/1.8/svn.ref.reposhooks.post-commit.html
repository_path=$1 # Repository path
revision=$2 # Revision number created by the commit
transaction=$3 # Name of the transaction that has become the revision triggering the post-commit hook.

remove=$(($revision - $ArchiveRetain))
if [ $remove -lt 0 ];
then
    exit 0
fi

function archive {
    cd $1
    for file in $(ls);
    do
        rev=$(($file + 0))
        if [[ $rev -le $remove ]];
        then
            rm -f $file;
        fi
    done
}

archive $repository_path/db/revs/0/
archive $repository_path/db/revprops/0/

